<?php

namespace SDF\BilletterieBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContraintesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContraintesRepository extends EntityRepository
{
}
