sdf_billetterie_administration_price_groups_list:
    path:     /
    defaults:
        _controller: SDFBilletterieBundle:Billetterie/Admin/Entities/PriceGroups:list
    methods: GET

sdf_billetterie_administration_price_group_new:
    path:     /new
    defaults:
        _controller: SDFBilletterieBundle:Billetterie/Admin/Entities/PriceGroups:new
    methods: GET

sdf_billetterie_administration_price_group_create:
    path:     /create
    defaults:
        _controller: SDFBilletterieBundle:Billetterie/Admin/Entities/PriceGroups:create
    methods: POST
