index_page:
    path:     /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: sdf_billetterie_homepage
    methods: GET

sdf_billetterie:
    resource: @SDFBilletterieBundle/Resources/config/routing/billetterie.yml
    prefix: /billetterie